### ISSUE TITLE
Using an ESP8266 over ESP32

### ISSUE THREAD

**Issue by ceres-c** [shinyquagsire23/ESP32-GBA-SIO#1]
Hi,
I've been thinking about doing something similar to this project with an ESP8266 and I stumbled upon your project by chance.
Why have you chosen to use the ESP32? Was it a calculated choice due to missing technical features I'm unaware of or a trivial reason ("I have a 32 at home right now and I'm going to use it")?
Thanks

**Comment by shinyquagsire23** [comment]
I used an ESP32 more for the extra pins, I have an 8266 but it's the 8-pin version which is a bit more limited I guess.

**Comment by ceres-c** [comment]
Yep, it indeed is more limited since it should be the ESP01 with 2 GPIO ports.
I have a mcudevkit which is based on ESP12 and should have more than enough ports. Thanks for clarifying it, I feared I might have missed some obvious limitation.
